### ISSUE TITLE
Additional data

### ISSUE THREAD

**Issue by cpacia** [blockstack/blockstack-resolver#109]
It would be nice if the resolver also returned:
- The data hash (for our purposes at openbazaar we could probably skip the record information and just set our guid as the data hash. we could even add an option to the api call whether to fetch and return the record or only return the data hash).
- The txid the transaction was included in (so we can build our own transactions for updating and transferring names). 
- The block height this transaction is included in (so we can decide whether to trust it or not).

**Comment by shea256** [comment]
Great call @cpacia I'm tagging @muneeb-ali and @jcnelson so they can see this as well.

**Comment by muneeb-ali** [comment]
@cpacia Other than the block height, the other two are already returned by the Blockstack server and we can include these in the resolver results as well. 

We've had some discussions for showing "no. of confirmations" (I think that's what you mean by block height) and I believe @jcnelson already has that marked as a new-feature.

**Comment by jcnelson** [comment]
I think you'll be interested in the advanced `get_name_blockchain_history` operation:
```
$ blockstack get_name_blockchain_history testregistration001.id
{
    "419771": [
        {
            "address": "16CtpS8LhmW3bGtVC69UGZ3wSwvi95BE8E", 
            "block_number": 419738, 
            "consensus_hash": "a06562670b300a72428fd4f60d6ca792", 
            "expire_block": 472366, 
            "first_registered": 419771, 
            "importer": null, 
            "importer_address": null, 
            "last_renewed": 419771, 
            "name": "testregistration001.id", 
            "op": ":", 
            "op_fee": 6250, 
            "opcode": "NAME_REGISTRATION", 
            "preorder_block_number": 419738, 
            "revoked": false, 
            "sender": "76a914391875b7835408bfe7fb2a01574ce810664d20a888ac", 
            "sender_pubkey": "04c77f262dda02580d65c9069a8a34c56bd77325bba4110b693b90216f5a3edc0bebc8ce28d61aa86b414aa91ecb29823b11aeed06098fcd97fee4bc73d54b1e96", 
            "txid": "461e7ec7c987efe1d3ab4dbfce48c82cd75f5c67cea512261413713fe845a976", 
            "value_hash": null, 
            "vtxindex": 10
        }
    ], 
    "419842": [
        {
            "address": "16CtpS8LhmW3bGtVC69UGZ3wSwvi95BE8E", 
            "block_number": 419738, 
            "consensus_hash": "a06562670b300a72428fd4f60d6ca792", 
            "expire_block": 472366, 
            "first_registered": 419771, 
            "importer": null, 
            "importer_address": null, 
            "last_renewed": 419771, 
            "name": "testregistration001.id", 
            "op": "+", 
            "op_fee": 6250, 
            "opcode": "NAME_UPDATE", 
            "preorder_block_number": 419738, 
            "revoked": false, 
            "sender": "76a914391875b7835408bfe7fb2a01574ce810664d20a888ac", 
            "sender_pubkey": "04c77f262dda02580d65c9069a8a34c56bd77325bba4110b693b90216f5a3edc0bebc8ce28d61aa86b414aa91ecb29823b11aeed06098fcd97fee4bc73d54b1e96", 
            "txid": "6a3a8ff9526c8309c8e66ead60d747f0edb3f95905eeb3c9f4bbec94d818794c", 
            "value_hash": "968160977cda3f6c792963270b8f720a475f3527", 
            "vtxindex": 8
        }
    ]
}
```
The fields you'd be interested in are the block heights (the keys in this dict), the transactions that issued the name operations (`txid`), the kind of name operation (`opcode`), and the data hash at the time just after the operation completed (`value_hash`).

**Comment by muneeb-ali** [comment]
@cpacia You should check out the new Blockstack API that has this info 

For example: https://core.blockstack.org/#naming_name_history

The resolver was merged with [blockstack-core](/blockstack/blockstack-core) and feel free to start any future issues there -- thanks!
