### ISSUE TITLE
resolver on Heroku

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-resolver#42]
As far as I understand, the resolver is only deployed on AWS right now with apache servers. Is that correct?

I see a Procfile in the repo. Has it ever been run on Heroku? Do we want it to be compatible with Heroku?

If so, then we should update the Procfile to work with a scalable web server like Gunicorn, rather than work with the development-only default Flask server.

We could update the Procfile from this:

`web: ./runserver.py`

to this:

`web: gunicorn runserver:app --workers 3`

or something more robust like this:

`web: gunicorn runserver:app --workers $WEB_CONCURRENCY --preload --timeout 10 --max-requests 1200`

so long as the deployer runs the following:

`heroku config:set WEB_CONCURRENCY=3`

**Comment by muneeb-ali** [comment]
I've only tested on AWS with Apache. Not on Heroku. @smurthas tested on Heroku sometime back

I can look into deploying on Heroku later.

**Comment by shea256** [comment]
Oh ok cool. On AWS it's apache + mod_wsgi, is that correct? I should learn how apache works sometime.

**Comment by muneeb-ali** [comment]
Yep, correct. apache + mod_wsgi

**Comment by smurthas** [comment]
Yes, as of December 2014, it ran on Heroku. See #5 for the small set of changes I made to get it running.

**Comment by shea256** [comment]
OK yes I remember this, thanks.

Was pointing out above that the Procfile should be updated to use a production web server like Gunicorn.

**Comment by muneeb-ali** [comment]
Started a feature request in Blockstack Core: https://github.com/blockstack/blockstack-core/issues/385

Closing this issue.
