### ISSUE TITLE
More useful errors

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-resolver#79]
When something isn't working: for example: the DHT mirror is inaccessible or there's a problem with blockstore, the resolver returns `[]` instead of information about what isn't working. It would be great to have more verbose errors.

**Comment by muneeb-ali** [comment]
Maybe we should have a 'error' field in the reply?

**Comment by shea256** [comment]
Yes, can we copy over all of the error reporting rules we have in api.onename.com?

**Comment by shea256** [comment]
Looks like this is the location where the error is being returned: https://github.com/blockstack/blockstack-resolver/blob/master/resolver/server.py#L302

**Comment by muneeb-ali** [comment]
@larrysalibra we plan to consolidate the blockstack-server, resolver, search, and a HTTP API. I think we should discuss error reporting in that context instead of fixing the resolver which is on its way out.

The error reporting on the HTTP API is a good start and we can refine it.

**Comment by larrysalibra** [comment]
@larrysalibra makes sense to me.

**Comment by shea256** [comment]
@muneeb-ali I'd put in a quick fix on this, though, especially since Larry is utilizing it now.

Could be really simple like this:

```python
@app.errorhandler(500)
def internal_error(error):
    return make_response(jsonify({'error': 'Internal Server Error'}), 500)
```

**Comment by muneeb-ali** [comment]
Happy to put a quick Internal Server Error there. It doesn't really solve the problem though. 

I think the main point here is visibility into what went wrong. To me, Internal Server Error gives the same amount of information as [] (other than changing the format and making it nicer). What we want to know is visibility into questions like did something go wrong with the blockstack-server? If it did what happened. Did something go wrong with the DHT, if yes then what? Which leads to a discussion about how to best propagate errors through different systems.

**Comment by shea256** [comment]
This at least fixes the one problem, which is that the user of the resolver at least expects to get back a JSON object with an "error" field inside of it. I remember I ran into this problem several times before and it prevents the need for additional checks for consumers of the endpoint.

Of course, additional visibility into what is going wrong would be very helpful and yes, we could provide additional insight into specific issues with the server we come out with later.

**Comment by muneeb-ali** [comment]
Added

**Comment by shea256** [comment]
Nice! I think there's a line missing, though:
https://github.com/blockstack/blockstack-resolver/blob/73fe5701680b47bd6e2c9d57795399f82c106a2a/resolver/server.py#L303

**Comment by larrysalibra** [comment]
The other problem is that other error conditions: like problems with `blockstack-server` not running or experiencing some other don't generate an internal server error. 

For example, this looks like the code that's executed when blockstack client has a problem returning an empty JSON object:

https://github.com/blockstack/blockstack-resolver/blob/master/resolver/server.py#L143

While that response doesn't appear to get cached in memcached, it does get cached at a higher level in my stack because what is actually error condition is generating a `200` response.

**Comment by muneeb-ali** [comment]
@larrysalibra I've added the blockstack-server timeout error. Let me know if there is anything else that is immediately useful. Would love to chat about error reporting in general for the consolidated server I mentioned earlier.

**Comment by larrysalibra** [comment]
@muneeb-ali Thanks so much! Sure happy to chat. Closing this issue for now.
