### ISSUE TITLE
Ubuntu 15.10 Error

### ISSUE THREAD

**Issue by scriptzteam** [blockstack/blockstack-resolver#97]
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.

**Comment by muneeb-ali** [comment]
Thanks for reporting this. Twisted should no longer be required and I'm going to update that.

This error usually occurs when you're trying to install inside a virtualenvironment (are you?) because of a conflict. You can come out of the virtualenvrionment, and uninstall twisted from outside of the virtualenvironment. After that Twisted install inside the virtualenvironment works.

Let me know if this works.

**Comment by lxw0109** [comment]
@muneeb-ali 
I encountered the "ImportError" as scriptzteam, and I do install the blockstack tool inside a virtualenvironment. </br>
So I tried again in another computer(not virtualenvironment). But the Error showed again. How can I fix it?
If in a virtualenvironment, how to "uninstall twisted from **outside** of the virtualenvironment"?.
Thank you~

**Comment by lxw0109** [comment]
Hi, @scriptzteam 
Did you solve the "ImportError" mentioned above? Could you please share with me how to solve this problem?

**Comment by muneeb-ali** [comment]
@lxw0109 can you paste the stack trace of the error? Thanks,

**Comment by muneeb-ali** [comment]
Also, if this error occurred while installing blockstack can you please start an issue on https://github.com/blockstack/blockstack-cli/issues instead of here?

**Comment by lxw0109** [comment]
Thank you, @muneeb-ali 
My Issue is presendted [here]( https://github.com/blockstack/blockstack-cli/issues/70)

**Comment by muneeb-ali** [comment]
@scriptzteam @lxw0109 Thanks for reporting this earlier. I wanted to update you guys that the resolver was merged with Blockstack Core. You can read the docs and test API endpoints at: https://core.blockstack.org.

You can deploy your own node by following the [install instructions](https://github.com/blockstack/blockstack-core/blob/api/docs/install-api.md).

Closing this issue. Feel free to open new issues in the blockstack-core repo -- thanks!
